version: "3"
services:
  php:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    image: dealer-php
    container_name: dealer-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./laravel/:/var/www/html/
    networks:
      - app-network

  nginx:
    depends_on:
      - php
      - node
    image: nginx:alpine
    container_name: dealer-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./laravel/:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  node:
    image: node:19-bullseye-slim
    container_name: dealer-node
    working_dir: /var/www/html
    volumes:
      - ./laravel/:/var/www/html/
    command: bash -c "npm install && npm run watch"
    networks:
      - app-network

  mysql:
    env_file:
      - .env
    container_name: dealer-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
